- name: "Create dir for jenkins image build"
  file:
    path: "{{ ci.home }}/jenkins/docker"
    state: directory
- name: "Prepare jenkins docker file"
  template:
    src: Dockerfile.j2
    dest: "{{ ci.home }}/jenkins/docker/Dockerfile"
- name: "Build  custom jenkins image"
  docker_image:
    name: jenkins-docker:{{ jenkins.version }}
    path: "{{ ci.home }}/jenkins/docker"
    state: present
- name: "Start jenkins container"
  docker_container:
    name: jenkins
    image: jenkins-docker:{{ jenkins.version }}
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "{{ jenkins.port }}:8080"
    networks:
      - name: '{{ ci.docker.network }}'
- name: "Create jenkins service descriptor"
  template:
    src: jenkins-ci.service.j2
    dest: /etc/systemd/system/jenkins-ci.service
- name: "Enable jenkins service"
  service:
    name: jenkins-ci
    enabled: yes
    state: started
